---
# https://pre-commit.com/#installation
default_stages: [commit, push]
default_language_version:
  # force all unspecified Python hooks to run python3
  python: python3
minimum_pre_commit_version: '2.18.1'
repos:
  - repo: meta
    hooks:
      - id: identity
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      #- id: check-added-large-files
      #- id: check-case-conflict
      #- id: check-executables-have-shebangs
      #- id: check-merge-conflict
      #- id: check-shebang-scripts-are-executable
      #- id: check-vcs-permalinks
      #- id: check-yaml
      #- id: destroyed-symlinks
      #- id: detect-aws-credentials
      #  args: [--allow-missing-credentials]
      #- id: detect-private-key
      #- id: end-of-file-fixer
      #- id: fix-byte-order-marker
      #- id: forbid-submodules
      #- id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: ^static/.*$
